name: CI

on:
  push:
    paths:
      - 'tfx_addons/**'
      - '.github/workflows/ci.yml'
      - 'setup.py'
      - 'pyproject.toml'
    branches:
      - main
      - r*
  pull_request:
    paths:
      - 'tfx_addons/**'
      - '.github/workflows/ci.yml'
      - 'setup.py'
      - 'pyproject.toml'
    branches:
      - main
      - r*

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      # Test for several versions of TFX in parallel
      # keep constraints in sync with version.py
      # NB(gcasassaez): We have to add tensorflow here to avoid issues on resolution.
      matrix:
        depconstraint: 
          - "tfx~=1.4.0 tensorflow~=2.6.0"
          - "tfx~=1.8.0 tensorflow~=2.8.0"
        extras: ["all, test"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache python environment
      uses: actions/cache@v2
      with:
        # Cache pip
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding setup.py + TFX version
        key: ${{ runner.os }}-pip-${{ matrix.depconstraint }}-${{ hashFiles('tfx_addons/version.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.depconstraint }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==22.1.1 wheel
        python -m pip install -e ".[${{ matrix.extras }}]" ${{ matrix.depconstraint }}
    - name: Run tests
      run: pytest tfx_addons
