name: TFX Addons package CI

on:
  push:
    paths:
      - 'tfx_addons/**'
      - '.github/workflows/ci.yml'
      - 'setup.py'
      - 'pyproject.toml'
    branches:
      - main
      - r*
  pull_request:
    paths:
      - 'tfx_addons/**'
      - '.github/workflows/ci.yml'
      - 'setup.py'
      - 'pyproject.toml'
    branches:
      - main
      - r*

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      # Test for several versions of TFX in parallel
      matrix:
        # ToDo(casassg): Remove future from here once resolved upstream: https://github.com/tensorflow/transform/issues/257
        depconstraint: ["tfx~=1.4.0 tensorflow~=2.6.0 future", "tfx~=1.6.0 tensorflow~=2.7.0"]
        extras: ["all, test"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache python environment
      uses: actions/cache@v2
      with:
        # Cache installed dependencies
        path: ${{ env.pythonLocation }}
        # Look to see if there is a cache hit for the corresponding setup.py + TFX version 
        key: ${{ env.pythonLocation }}-pip-${{ matrix.depconstraint }}-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ env.pythonLocation }}-pip-${{ matrix.depconstraint }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -e ".[${{ matrix.extras }}]" ${{ matrix.depconstraint }}
    - name: Run tests
      run: pytest tfx_addons
  
